name: alchemist
favicon: null
layout_spectrum: 0.8215085461270064
typography_spectrum: 0.48569153738208115
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.19228350091725588
  lightness: 0.594787864247337
  saturation: 0.607378757558763
  rhythmicContrast: 0.749283701647073
purpose: []
